"""
09_extended_headtracking.py  [Report 2]
─────────────────────────────────────────────────────────────────────────────
Analyses the three rotation axes that were NOT used in Report 1:
  • Pitch  (RotationSpeedX — up/down head movement)
  • Roll   (RotationSpeedZ — lateral head tilt)
  • Total  (RotationSpeedTotal — magnitude of full 3-D rotation vector)

For comparison, yaw (RotationSpeedY, the Report 1 primary metric) is also
included so all four axes appear side-by-side.

For each axis × video combination the script runs:
  1. Descriptive statistics (mean, SD, median) per depression group
  2. Kruskal-Wallis H test across the three depression groups
  3. Spearman correlation between PHQ-9 score and axis mean

OUTPUT
  outputs/report2_extended_headtrack.csv  — full results table
  (Figures are generated by 13_figures_report2.py)
"""

import pandas as pd
import numpy as np
from scipy import stats

from config import GROUP_ORDER, VIDEO_NAMES
from data_loader import build_headtrack

# ── Load data ─────────────────────────────────────────────────────────────────
print("=" * 65)
print("09  Extended Head-Tracking: Pitch, Roll, Total Speed")
print("=" * 65)

ht = build_headtrack()
print(f"  Loaded wide table: {ht.shape[0]} participants\n")

AXES = ["yaw", "pitch", "roll", "total"]
AXIS_LABELS = {
    "yaw":   "Yaw   (RotationSpeedY)",
    "pitch": "Pitch (RotationSpeedX)",
    "roll":  "Roll  (RotationSpeedZ)",
    "total": "Total (RotationSpeedTotal)",
}

# ── Per-axis × per-video analysis ─────────────────────────────────────────────
rows_out = []

for ax in AXES:
    print(f"\n{'─'*65}")
    print(f"  Axis: {AXIS_LABELS[ax]}")
    print(f"  {'Video':<28} {'Min M':>7} {'Mld M':>7} {'MS M':>7}"
          f" {'H':>7} {'p':>8}  {'Sig':>4}  {'ρ(PHQ)':>7} {'p':>8}")
    print(f"  {'─'*90}")

    for v in range(1, 6):
        col = f"v{v}_mean_{ax}"
        if col not in ht.columns:
            continue

        # Per-group data
        grp_data = [ht[ht["depression_group"] == g][col].dropna().values
                    for g in GROUP_ORDER]

        if not all(len(g) >= 3 for g in grp_data):
            continue

        grp_means = [float(g.mean()) for g in grp_data]
        grp_sds   = [float(g.std())  for g in grp_data]
        overall_m = float(ht[col].mean())
        overall_sd = float(ht[col].std())

        # Kruskal-Wallis
        H, p_kw = stats.kruskal(*grp_data)
        sig = ("***" if p_kw < .001 else
               "**"  if p_kw < .01  else
               "*"   if p_kw < .05  else "ns")

        # Spearman vs PHQ-9
        sub = ht[["score_phq", col]].dropna()
        rho, p_sp = stats.spearmanr(sub["score_phq"], sub[col]) if len(sub) >= 10 \
                    else (np.nan, np.nan)

        direction = ("↓ Mod-Sev < Min" if grp_means[2] < grp_means[0]
                     else "↑ Mod-Sev ≥ Min")

        print(f"  V{v}: {VIDEO_NAMES[v]:<24}"
              f" {grp_means[0]:>7.2f} {grp_means[1]:>7.2f} {grp_means[2]:>7.2f}"
              f" {H:>7.3f} {p_kw:>8.4f}  {sig:>4}  {rho:>7.3f} {p_sp:>8.4f}"
              f"  {direction}")

        rows_out.append({
            "axis":       ax,
            "video":      f"V{v}",
            "video_name": VIDEO_NAMES[v],
            "overall_M":  round(overall_m,  3),
            "overall_SD": round(overall_sd, 3),
            "Min_M":      round(grp_means[0], 3),
            "Min_SD":     round(grp_sds[0],   3),
            "Mild_M":     round(grp_means[1], 3),
            "Mild_SD":    round(grp_sds[1],   3),
            "ModSev_M":   round(grp_means[2], 3),
            "ModSev_SD":  round(grp_sds[2],   3),
            "H":          round(H,    4),
            "p_kruskal":  round(p_kw, 4),
            "sig_kw":     sig,
            "direction":  direction,
            "rho_phq":    round(float(rho), 4) if not np.isnan(rho) else np.nan,
            "p_spearman": round(float(p_sp), 4) if not np.isnan(p_sp) else np.nan,
        })

# ── Save results ──────────────────────────────────────────────────────────────
from config import OUTPUT_DIR
out_path = f"{OUTPUT_DIR}/report2_extended_headtrack.csv"
pd.DataFrame(rows_out).to_csv(out_path, index=False)
print(f"\n  → Saved: {out_path}")

# ── Console summary ───────────────────────────────────────────────────────────
print("\n" + "=" * 65)
print("  Summary: significant Kruskal-Wallis tests (p < .05)")
print("=" * 65)
sig_tests = [r for r in rows_out if r.get("p_kruskal", 1) < 0.05]
if sig_tests:
    for r in sig_tests:
        print(f"  {r['axis'].upper():6}  {r['video']}  H={r['H']:.3f}  p={r['p_kruskal']:.4f}")
else:
    print("  None — no Kruskal-Wallis test reached p < .05 across any axis × video.")

print("\n  Summary: Spearman |ρ| range by axis (across V1–V5):")
for ax in AXES:
    rhos = [abs(r["rho_phq"]) for r in rows_out
            if r["axis"] == ax and not np.isnan(r["rho_phq"])]
    if rhos:
        print(f"  {ax.upper():6}: |ρ| in [{min(rhos):.3f}, {max(rhos):.3f}]")

print("\nDone — 09_extended_headtracking.py")
